version: '3'
services:
  front:
    container_name: NAMEF
    image: REGISTRY/NAMEF:VERSION
    ports:
      - "3000:3000"
    environment:
      - PRODUCTS_SERVICE=NAMEP
      - SHOPPING_CART_SERVICE=NAMES
    depends_on:
      - products
      - shopping-cart
    restart: always
      
  products:
    container_name: NAMEP
    image: REGISTRY/NAMEP:VERSION
    ports:
      - "3001:3001"
    restart: always

  shopping-cart:
    container_name: NAMES
    image: REGISTRY/NAMES:VERSION
    ports:
      - "3002:3002"
    restart: always